### ISSUE TITLE
这怎么解决？

### ISSUE THREAD

**Issue by 635783796** [CSFelix/NodeJS-WhatsApp-Telegram-Bot#10]
![image](https://user-images.githubusercontent.com/70841795/225587249-e3702392-7099-4647-9782-66a2df0d2385.png)

**Comment by CSFelix** [comment]
Hello there, to run the code you need to install `PySocks` package with `pip` first. To do this, you can execute the command bellow in your command prompt:

```cmd
pip install PySocks
```

After that, the code should work out.

If you need any help, hit me up!!  👋👋

**Comment by 635783796** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 635783796** [comment]
> 你好，要运行你需要先安装`PySocks`包的代码`pip`。为此，您可以在命令提示符下执行以下命令：
> 
> ```batchfile
> pip install PySocks
> ```
> 
> 之后，代码应该可以运行了。
> 
> 如果您需要任何帮助，请联系我！！ 👋👋

已经解决了，谢谢！

**Comment by CSFelix** [comment]
You're welcome!! If you need anything else, hit me up!!
